color: red
fieldLayouts:
  b38c34f1-41bc-4534-982a-7d49e7426c12:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T09:25:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a44fc653-15fa-49d2-a34a-6aa909449b7a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T09:27:39+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: subText
            includeInCards: false
            instructions: null
            label: SubText
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e132159-fa59-466b-96ae-1a7ab52052c2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T09:27:39+00:00'
            elementCondition: null
            fieldUid: 35c35080-108d-485f-925f-407a5ab65a22 # Cover
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9d181c9-bab8-4c27-a841-862798e74e32
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 14eafa99-77fd-44d1-bd26-670c2cea1a19
        userCondition: null
handle: categories
hasTitleField: true
icon: align-center
name: Categories
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
