columnSuffix: null
handle: carousel
instructions: null
name: Carousel
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:5d45f9f4-7ab7-4459-926d-a8006cad4227' # Images
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 10
  minRelations: 1
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:5d45f9f4-7ab7-4459-926d-a8006cad4227' # Images
  restrictedLocationSubpath: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:5d45f9f4-7ab7-4459-926d-a8006cad4227' # Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
