columnSuffix: null
handle: category
instructions: null
name: Category
searchable: false
settings:
  maxLength: 255
  showLabelField: false
  showTargetField: false
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - 'section:ed7db658-eb24-45ba-b0c8-a5eb0ff97980' # Categories
  types:
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
